/**:
  ros__parameters:
    root_dir: /tmp/episode_recorder
    experiment_name: "pick_and_place"
    storage_id: mcap
    max_episode_duration: 0.0
    topics:
      - /follower/image_raw
      - /static_camera/image_raw
      - /follower/joint_states
      - /follower/forward_controller/commands
