follower:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      arm_forward_controller:
        type: forward_command_controller/ForwardCommandController

      arm_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      gripper_controller:
        type: parallel_gripper_action_controller/GripperActionController

  joint_state_broadcaster:
    ros__parameters:
      publish_rate: 50.0

  arm_trajectory_controller:
    ros__parameters:
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow_flex
        - wrist_flex
        - wrist_roll
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      allow_partial_joints_goal: false
      open_loop_control: false

      constraints:
        stopped_velocity_tolerance: 0.01

  arm_forward_controller:
    ros__parameters:
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow_flex
        - wrist_flex
        - wrist_roll
      interface_name: position

  gripper_controller:
    ros__parameters:
      joint: gripper
      allow_stalling: true
      # Optional: tune these later
      # max_velocity: 1.0
      # max_effort: 0.0
